[[dependencies]]
  branch = "master"
  name = "github.com/cznic/sqlite"

[[dependencies]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[dependencies]]
  name = "github.com/labstack/echo"
  version = "^3.1.0"

[[dependencies]]
  name = "github.com/labstack/gommon"
  version = ">=0.2.1, <1.0.0"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
